name: Ionic CI/CD with Cypress
on:
  pull_request:
     types: [opened, synchronize, reopened]
  

jobs:
  test-e2e:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ionic
        run: npm install -g @ionic/cli
      
      - name: Add env secrets
        env:
          ENVIRONNEMENTTS: ${{ secrets.ENVIRONNEMENTTS }}
        run: 
           echo "$KEYSTORE" | base64 --decode > src/environments/environment.ts

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: ionic build
          start: ionic serve

      