name: Ionic CI/CD with Cypress
on: push


jobs:
  test-e2e:
    runs-on: ubuntu-24.04
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: ionic build
          start: ionic serve

  build-release-apk:
    #needs: test-e2e
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Ionic and Capacitor dependencies
        run: npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic app
        run: ionic build --prod  # Build the web assets for the app

      - name: Copy web assets to Android project
        run: npx cap copy android  # Copy the built assets to the Android platform

      - name: Build Android APK (Debug)
        run: npx cap open android && ./platforms/android/gradlew assembleDebug  # Build debug APK

      - name: Build Android APK (Release)
        run: npx cap open android && ./platforms/android/gradlew assembleRelease  # Build release APK

      - name: Upload Dev APK
        uses: actions/upload-artifact@v4
        with:
            name: app-dev
            path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
            name: app-release
            path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk  # The unsigned release APK

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v4
        with:
            name: app-release-bundle
            path: platforms/android/app/build/outputs/bundle/release/app-release.aab  # Upload the AAB file for distribution