name: Ionic CI/CD with Cypress
on: push


jobs:
  test-e2e:
    runs-on: ubuntu-24.04
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: ionic build
          start: ionic serve

  build-release-apk:
    #needs: test-e2e
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 13.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: ionic cordova platform add android@latest

      - name: Build Android Dev APK
        run: ionic cordova build android

      - name: Build Android Release APK
        run: ionic cordova build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./platforms/android/
        run: ./gradlew bundle

      - name: Upload dev APK
        uses: actions/upload-artifact@v4
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: platforms/android/app/build/outputs/bundle/release/app.aab