name: Ionic CI/CD with Cypress
on: push


jobs:
  test-e2e:
    runs-on: ubuntu-24.04
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: ionic build
          start: ionic serve

  build-release-apk:
    #needs: test-e2e
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'

      - name: Install Ionic and Capacitor dependencies
        run: npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Install app dependencies
        run: |
            npm install
            npm run build

      - name: Build Ionic app
        env:
            KEYSTOREALIAS_PASS: ${{ secrets.KEYSTOREALIAS_PASS }}
            KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS}}
        run: |
            npx cap sync
            npx cap build android --keystorepath android.jks --keystorepass "$KEYSTORE_PASS" --keystorealias key0 --keystorealiaspass "$KEYSTOREALIAS_PASS" --androidreleasetype APK
    

      - name: Upload Dev APK
        uses: actions/upload-artifact@v4
        with:
          name: app-dev
          path: android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android/app/build/outputs/apk/release/app-release-signed.apk